baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Règles Élémentaires"

[params]
  display_popup_credit_menstruel = false
  display_popup_5ans = false
  display_popup_don = false
  display_popup_tribune = false
  display_popup_festival = false
  display_popup_barometre = false

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
[menu]
  [[menu.main]]
    identifier = "asso"
    name = "Qui sommes-nous ?"
    url = "/asso/chiffres"
    weight = 1
  [[menu.main]]
    identifier = "actions"
    name = "Nos actions"
    url = "/actions/collecter"
    weight = 2
  [[menu.main]]
    identifier = "agir"
    name = "Agir avec nous"
    url = "/agir/particulier/donner"
    weight = 3
  [[menu.main]]
    identifier = "particulier"
    name = "Particulier"
    url = "/agir/particulier/donner"
    parent = "agir"
    weight = 1
  [[menu.main]]
    identifier = "collecter-entreprise"
    name = "Collecter"
    url = "/agir/entreprise/#collecter"
    parent = "entreprise"
    weight = 1
  [[menu.main]]
    identifier = "sensibiliser-entreprise"
    name = "Sensibiliser"
    url = "/agir/entreprise/#sensibiliser"
    parent = "entreprise"
    weight = 2
  [[menu.main]]
    identifier = "dons-produits"
    name = "Dons produits"
    url = "/agir/entreprise/#dons-produits"
    parent = "entreprise"
    weight = 3
  [[menu.main]]
    identifier = "mecenat"
    name = "Mécénat"
    url = "/agir/entreprise/#mecenat"
    parent = "entreprise"
    weight = 4
  [[menu.main]]
    identifier = "association"
    name = "Association"
    url = "/agir/association/redistribuer"
    parent = "agir"
    weight = 3
  [[menu.main]]
    identifier = "collecter-collectivite"
    name = "Collecter"
    url = "/agir/collectivite/#collecter"
    parent = "collectivite"
    weight = 1
  [[menu.main]]
    identifier = "sensibiliser-collectivite"
    name = "Sensibiliser"
    url = "/agir/collectivite/#sensibiliser"
    parent = "collectivite"
    weight = 2
  [[menu.main]]
    identifier = "subventionner-collectivite"
    name = "Subventionner"
    url = "/agir/collectivite/#subventionner"
    parent = "collectivite"
    weight = 3
  [[menu.main]]
    identifier = "collecter-ecole"
    name = "Collecter"
    url = "/agir/ecole/#collecter"
    parent = "ecole"
    weight = 1
  [[menu.main]]
    identifier = "colleges"
    name = "Collèges et Lycées"
    url = "/agir/ecole/#colleges"
    parent = "ecole"
    weight = 2
  [[menu.main]]
    identifier = "universites"
    name = "Universités"
    url = "/agir/ecole/#universites"
    parent = "ecole"
    weight = 3