baseurl = "/"
languageCode = "fr-fr"
languageLang = "fr"
title = "Règles Élémentaires"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
[menu]
  [[menu.main]]
    identifier = "projet"
    name = "Découvrir le Projet"
    url = "/projet/mission"
    weight = 1
  [[menu.main]]
    identifier = "collecter"
    name = "Organiser une collecte"
    url = "/collecter/organiser"
    weight = 2
  [[menu.main]]
    identifier = "donner"
    name = "Donner des produits"
    url = "/donner/trouver"
    weight = 3
  # [[menu.main]]
  #   identifier = "actualites"
  #   name = "Actualités"
  #   url = "/"
  #   weight = 4
  [[menu.main]]
    identifier = "soutenir"
    name = "Soutenir l'association"
    url = "/soutenir/dons-financiers"
    weight = 4