backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "site/content/post" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   fields: # The fields each document in this collection have
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Intro Blurb", name: "description", widget: "text" }
  #     - { label: "Image", name: "image", widget: "image", required: false }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: "team" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Equipe" # Used in the UI, ie.: "New Post"
    folder: "site/data/team" # The path to the folder where the documents are stored
    identifier_field: "name"
    extension: toml
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Linkedin URL", name: "linkedin", widget: "string" }
      - { label: "Photo", name: "img", widget: "image" }
      - { label: "Biographie", name: "bio", widget: "text" }
  - name: "partenaires" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Partenaires" # Used in the UI, ie.: "New Post"
    folder: "site/data/partenaires" # The path to the folder where the documents are stored
    identifier_field: "name"
    extension: toml
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Nom", name: "name", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["redistributeur", "institutionnels", "industriels", "autres"] }
      - { label: "Lien", name: "link", widget: "string" }
      - { label: "Logo", name: "img", widget: "image" }
  - name: "projet"
    label: "Pages Projet"
    files:
      - file: "site/content/projet/actions.md"
        label: "Nos Actions"
        name: "actions"
        fields:
          - {label: Menu, name: menu, widget: hidden}
          - {label: Layout, name: layout, widget: hidden}
          - { label: Titre, name: title, widget: string }
          - { label: Illustration, name: illu, widget: image }
          - { label: Body, name: body, widget: markdown }
          - 
              label: "Actions"
              name: actions
              widget: list
              fields:
                - { label: "Titre", name: "title", widget: "string" }
                - { label: "Contenu", name: "content", widget: "markdown" }
                - { label: "Texte Bouton", name: "btn_text", widget: "string" }
                - { label: "Lien Bouton", name: "btn_link", widget: "string" }
                - label: "Illustrations"
                  name: "illu"
                  widget: "list"
                  field: {label: Image, widget: image}
